// Code generated by goyacc DO NOT EDIT.

package main

import __yyfmt__ "fmt"

import "math"

type yySymType struct {
	yys    int
	number float64
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault   = 57348
	yyEOFCode   = 57344
	yyErrCode   = 57345
	number      = 57346
	unary_minus = 57347

	yyMaxDepth = 200
	yyTabOfs   = -10
)

var (
	yyXLAT = map[int]int{
		45:    0,  // '-' (18x)
		57344: 1,  // $end (10x)
		42:    2,  // '*' (10x)
		43:    3,  // '+' (10x)
		47:    4,  // '/' (10x)
		94:    5,  // '^' (10x)
		41:    6,  // ')' (9x)
		40:    7,  // '(' (8x)
		57349: 8,  // expr (8x)
		57346: 9,  // number (8x)
		57350: 10, // result (1x)
		57348: 11, // $default (0x)
		57345: 12, // error (0x)
		57347: 13, // unary_minus (0x)
	}

	yySymNames = []string{
		"'-'",
		"$end",
		"'*'",
		"'+'",
		"'/'",
		"'^'",
		"')'",
		"'('",
		"expr",
		"number",
		"result",
		"$default",
		"error",
		"unary_minus",
	}

	yyReductions = []struct{ xsym, components int }{
		{0, 1},
		{10, 1},
		{8, 3},
		{8, 3},
		{8, 3},
		{8, 3},
		{8, 3},
		{8, 2},
		{8, 3},
		{8, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [19][]uint8{
		// 0
		{13, 7: 14, 12, 15, 11},
		{1: 10},
		{20, 9, 17, 19, 18, 21},
		{13, 7: 14, 28, 15},
		{13, 7: 14, 16, 15},
		// 5
		{1, 1, 1, 1, 1, 1, 1},
		{20, 2: 17, 19, 18, 21, 22},
		{13, 7: 14, 27, 15},
		{13, 7: 14, 26, 15},
		{13, 7: 14, 25, 15},
		// 10
		{13, 7: 14, 24, 15},
		{13, 7: 14, 23, 15},
		{2, 2, 2, 2, 2, 2, 2},
		{4, 4, 4, 4, 4, 21, 4},
		{5, 5, 17, 5, 18, 21, 5},
		// 15
		{6, 6, 17, 6, 18, 21, 6},
		{7, 7, 7, 7, 7, 21, 7},
		{8, 8, 8, 8, 8, 21, 8},
		{3, 3, 3, 3, 3, 3, 3},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Errorf(format string, a ...interface{}) error
	AppendError(err error)
	Errors() (warns []error, errs []error)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEOFCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer, parser *Parser) int {
	const yyError = 12

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	parser.yylval = yySymType{}
	yyS := parser.cache

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
		parser.cache = yyS
	}
	parser.yyVAL = &yyS[yyp+1]
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yychar = yylex1(yylex, &parser.yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		*parser.yyVAL = parser.yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if !ok || msg == "" {
				msg = "syntax error"
			}
			// ignore goyacc error message
			yylex.AppendError(yylex.Errorf(""))
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEOFCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
		parser.cache = yyS
	}
	parser.yyVAL = &yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			parser.result = yyS[yypt-0].number
		}
	case 2:
		{
			parser.yyVAL.number = yyS[yypt-2].number * yyS[yypt-0].number
		}
	case 3:
		{
			parser.yyVAL.number = yyS[yypt-2].number / yyS[yypt-0].number
		}
	case 4:
		{
			parser.yyVAL.number = yyS[yypt-2].number + yyS[yypt-0].number
		}
	case 5:
		{
			parser.yyVAL.number = yyS[yypt-2].number - yyS[yypt-0].number
		}
	case 6:
		{
			parser.yyVAL.number = math.Pow(yyS[yypt-2].number, yyS[yypt-0].number)
		}
	case 7:
		{
			parser.yyVAL.number = -yyS[yypt-0].number
		}
	case 8:
		{
			parser.yyVAL.number = yyS[yypt-1].number
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, parser.yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
